services:
  clt:
    image: ingeniouslycrazy/bootstrap-clt:latest
    init: false
    volumes:
      - ./ansible:/srv/ansible
      - ./oci/ansible/known_hosts:/root/.ssh/known_hosts
      - ./terraform:/srv/terraform
      - ./terraform.tfstate:/srv/terraform.tfstate
      - oci_secrets:/srv/secrets
      - ./export:/srv/export
    env_file:
      - ./export/.cltenv

volumes:
  oci_secrets: