---
- name: "Create Linux user {{ proxmox_sa_name }}"
  ansible.builtin.user:
    name: proxmox_sa_name
    password: proxmox_sa_password
    state: present
    update_password: on_create

- name: "Create Proxmox user {{ proxmox_sa_name }}"
  ansible.builtin.shell: "pveum user add {{ proxmox_sa_name }}@pam --password {{ proxmox_sa_password }} >> /home/{{ proxmox_sa_name }}/somelog.txt"
  args:
    creates: "/home/{{ proxmox_sa_name }}/somelog.txt"
