- name: Preflight check
  hosts: node01,localhost
  gather_facts: false
  tasks:
    - name: Test terraform
      shell: terraform --version
      register: tf_version
      failed_when: "'Terraform' not in tf_version.stdout"
      changed_when: false
      delegate_to: localhost
    - name: Test SSH connection to VM Management
      ping:
      delegate_to: node01
